### ISSUE TITLE
docs do not works

### ISSUE THREAD

**Issue by Edgar06ka** [dirigeants/klasa#1039]
### Describe the issue
[docs](https://klasa.js.org/#/docs/klasa/master/Getting%20Started/GettingStarted) do not work
### Code or steps to reproduce

```js
TypeError: can't access property "sort", a.classes is undefined
```

**Comment by kyranet** [comment]
We know the docs are broken for master and stable, we're currently working on rewriting the site from the ground up

To view @klasa/core docs: <https://dirigeants.github.io/core/index.html>
To view klasa master docs: <https://dirigeants.github.io/klasa/index.html>
To view klasa stable docs: <https://klasa.js.org/#/docs/klasa/v0.5.0/Getting%20Started/GettingStarted>

**Comment by Edgar06ka** [comment]
thanks
