### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by Jonyk56** [dirigeants/klasa#1043]
### Describe the issue

the package is broken/ won't build

### Code or steps to reproduce

install most recent version of klasa ( github/0.5.0 )

run code that uses klasa ( causes entry point error because klasa won't build)

```js

```

### Expected and actual behavior
 no errors 

### Further details

- **@klasa/core version**: n/a
- **node.js version**:12.0.0
- **Klasa version**:0.5.0
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: 3dd2cbdca0f4a71f0dedddf6bbd779b3173f9de0

**Comment by kyranet** [comment]
Install stable instead.

```ssh-session
# Install with npm
$ npm i klasa discord.js

# Install with yarn
$ yarn add klasa discord.js
```

**Comment by Jonyk56** [comment]
how about for dev?
