### ISSUE TITLE
Documentation is not opening

### ISSUE THREAD

**Issue by codetheorem** [dirigeants/klasa#1054]
### Describe the issue
Documentation on the website is not opening.
![image](https://user-images.githubusercontent.com/54779517/85267874-68394f80-b493-11ea-9fcc-9ae317350210.png)

### Further details

- **@klasa/core version**:
- **node.js version**:
- **Klasa version**:
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
Duplicate of #1039
