### ISSUE TITLE
Incorrect Docs Link and subsequent GitHub Link

### ISSUE THREAD

**Issue by nyjr10025** [dirigeants/klasa#1098]
### Describe the issue

No documentation is shown when forwarded to docs link, by clicking on docs button on: 
https://klasa.js.org/#/
Then, when trying to go to the github page after clicking the docs link:
https://klasa.js.org/#/docs/klasa/stable/Getting%20Started/GettingStarted
I get a dead git hub url 
https://github.com/dirigeants/klasa/tree/stable

### Code or steps to reproduce

1. Go to https://klasa.js.org/#/
2. Click on Docs (first issue)
3. Click on Github Link (second issue)

### Expected and actual behavior
Expected behavior:
Github link: https://github.com/dirigeants/klasa/tree/master
Docs link: maybe auto link it to v0.5.0 (stable and master show no documentation)

### Further details

- **@klasa/core version**:
- **node.js version**:
- **Klasa version**:
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by KunoichiZ** [comment]
They know the docs are broken for master and stable, they're currently working on rewriting the site from the ground up

To view @klasa/core docs: https://dirigeants.github.io/core/index.html
To view klasa master docs: https://dirigeants.github.io/klasa/index.html
To view klasa stable docs: https://klasa.js.org/#/docs/klasa/v0.5.0/Getting%20Started/GettingStarted

**Comment by nyjr10025** [comment]
Ahh I apologize, just a new user to Klasa. I'll close out the issue. Thanks @KunoichiZ for the links and heads up
