### ISSUE TITLE
Typings Bug

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#137]
### Describe the issue
It isn't a huge breaking bug, but something I thought worth mentioning. Honestly, i am not even sure if this is something that can even be fixed.

Typings automatically begin saying `BOTNAME is typing...` however, it does not take into consideration where the bot is sending the message. For example, if someone runs a command in a channel the bot will say the typings BUT that command actually sends a message in another channel. Its confusing as it seems to cause users to think the bot has broke until they realize oh the message came here.

P.S. This is not breaking just something to make it less inconvenient in those rare circumstances.

### Code or steps to reproduce

```js
1) Enable Typings
2) Run a command that sends a message to different channel 

```

### Expected an actual behaviour
Typings should occur on the channel where the bot types.

### Further details

- **discord.js version**: latest
- **node.js version**: 9+
- **Klasa version**: latest
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:

**Comment by bdistin** [comment]
There is no way to know where you intend to send a message during the time it types. Typing is just an indication that your bot has seen valid input, and is working in the channel where the valid input was seen.
