### ISSUE TITLE
Bug: RichDisplays in DMs Destroy Logs

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#147]
### Describe the issue

Having a RichDisplay sent in a DM will cause havoc on your logs. The commands work perfectly. The rich display works perfectly. The pages change perfectly. It does everything that it should do but it keeps sending this error to your log for every reaction that clicked. So if a user clicks 2-3 times and you have thousands of users on a popular command it destroys logs. 

There should be a way to catch/ignore this error somehow because as I said the command works perfectly. The users have no issues. But the developer logs are insanely spammed.

```javascript
Uncaught Promise Error: 
DiscordAPIError: Cannot execute action on a DM channel
 at item.request.gen.end (node_modules/discord.js/src/rest/handlers/RequestHandler.js:79:65)
at then (node_modules/snekfetch/src/index.js:218:21)
 at <anonymous>
 at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

### Code or steps to reproduce

```
1) Create a rich display command to run in a DM
2) Use reactions
3) Check logs
```

### Expected an actual behaviour

Either a workaround or some sort of method to avoid this log is necessary. The only issue here is with the error log and not the RichDisplay or command. All i really need is a way to ignore this error from my console.

### Further details

- **discord.js version**: latest
- **node.js version**: 9+
- **Klasa version**: latest
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
I strongly believe that issue is caused exactly in this line:

https://github.com/dirigeants/klasa/blob/1ce5d87a3a8d2737090c59c2d7fc6a32af891eb5/src/lib/util/ReactionHandler.js#L179

And here aswell:

https://github.com/dirigeants/klasa/blob/1ce5d87a3a8d2737090c59c2d7fc6a32af891eb5/src/lib/util/ReactionHandler.js#L332

This issue could be solved by checking permissions. I'll try to add a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) that checks the permissions to solve this issue.

**Comment by bdistin** [comment]
This is why #149 149 exists.

**Comment by kyranet** [comment]
Whilst #149 is probably a Discord Client bug (ratelimits, connection issues...), this is not, this issue is caused by the lack of MANAGE_MESSAGES permission in DM channels. Locking such feature to guilds is a bad idea, and I also wanted to use RichDisplay in DMs for latter projects.

**Comment by bdistin** [comment]
149 is not because of a discord client bug; it only effects the menu when a reaction is added, which is why manage messages is **Required**

**Comment by kyranet** [comment]
Can you elaborate that response, please?

I could reproduce 149 only when I had network hiccups or was reacting too fast, and I was able to reproduce this even in guilds with full permissions, not only in DMs nor without permissions.
