### ISSUE TITLE
Bug: RichDisplay Requiring 2 Reaction Taps To Change Page

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#149]
### Describe the issue
With the fix of #147 it led to a new issue where the reaction needs to be tapped twice. I believe it occurs because now there is no way to remove the reaction automatically so you have to a) remove b) add new reaction. 

EDIT: Oops sorry I wasn't saying the fix caused it just revealed that it needs 2. Even before the fix this issue occurred because the bot couldn't remove the reactions so they still had to click twice. This fix simply revealed this issue more to me.

### Code or steps to reproduce

```js
1) Create a richdisplay to run in DM
2) run the command and go to page 2
3) try to go to page 3 but it wont
4) click again and it will go to page 3
```

### Expected an actual behaviour
The RichDisplay when it lacks perms to remove reactions could work when the user removes a reaction to move to next page

### Further details

- **discord.js version**: latest
- **node.js version**: 9+
- **Klasa version**: latest
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
I cannot reproduce this issue in latest master nor with the commit hash `be02875f05246f73ecc2b0cb58409426b2309dbb` from discord.js.

Although I also recognize I have seen this issue personally a while ago, being related to the Discord client and/or lag.

What do I mean? There are some special cases where you send a reaction, your Discord Client (the application, PC or mobile) sends the API request to add a reaction, but for some reason it fails (connection issues, the message doesn't exist...) and "removes" the reaction visually. This point will be crossed out if you don't see any error log in the console (`Ctrl` + `Shift` + `I`) when you add the reaction and automatically gets removed.

**Comment by bdistin** [comment]
This is the reason #147 exists.
