### ISSUE TITLE
Proposal: Better wildcard support in Cron

### ISSUE THREAD

**Issue by kyranet** [dirigeants/klasa#157]
### Describe the proposal

With the PR #156 we have implemented [Cron](https://en.wikipedia.org/wiki/Cron), however, we wanted to have a fully functional Cron before pulishing it and implement the rest of features. Currently, we're missing five non-standard wildcards:

**Edit**: Added `Done` column to the wildcard table and a list of commits implementing the new wildcards.

| Done | Wildcard | Description |
| :---: | :---: | :---: |
| - | `L` | 'L' stands for "last". When used in the day-of-week field, it allows you to specify constructs such as "the last Friday" ("5L") of a given month. In the day-of-month field, it specifies the last day of the month. |
| - | `W` | The 'W' character is allowed for the day-of-month field. This character is used to specify the weekday (Monday-Friday) nearest the given day. As an example, if you were to specify "15W" as the value for the day-of-month field, the meaning is: "the nearest weekday to the 15th of the month." So, if the 15th is a Saturday, the trigger fires on Friday the 14th. If the 15th is a Sunday, the trigger fires on Monday the 16th. If the 15th is a Tuesday, then it fires on Tuesday the 15th. However, if you specify "1W" as the value for day-of-month, and the 1st is a Saturday, the trigger fires on Monday the 3rd, as it does not 'jump' over the boundary of a month's days. The 'W' character can be specified only when the day-of-month is a single day, not a range or list of days. |
| ✅ | `?` | In some implementations, used instead of '*' for leaving either day-of-month or day-of-week blank. Other cron implementations substitute "?" with the start-up time of the cron daemon, so that `? ? * * * *` would be updated to `25 8 * * * *` if cron started-up on 8:25am, and would run at this time every day until restarted again. |
| - | `#` | '#' is allowed for the day-of-week field, and must be followed by a number between one and five. It allows you to specify constructs such as "the second Friday" of a given month. For example, entering "5#3" in the day-of-week field corresponds to the third Friday of every month. |
| ✅| `H` | 'H' is used in the Jenkins continuous integration system to indicate that a "hashed" value is substituted. Thus instead of '20 * * * *' which means at 20 minutes after the hour every hour, 'H * * * *' indicates that the task is performed every hour at an unspecified but invariant time. This allows spreading out tasks over time. |

From the [Wikipedia page](https://en.wikipedia.org/wiki/Cron).

We also support nonstandard predefined scheduling definitions, however, `@yearly` is supported where `@annually` isn't. (✅).

### Implementation

- [[`4b4a42ad0f`](https://github.com/dirigeants/klasa/commit/4b4a42ad0f056fce74ecf7c32a75a81b44f477db)] Fixed the wildcard `?`. (bdistin)
- [[`692e485d2b`](https://github.com/dirigeants/klasa/commit/692e485d2b7af5bf2b1d29c9e2dc4871f2e04f06)] Implemented the wildcards `?`, `H`, and the scheduling definition `@annually`. (bdistin)

### Further details

- [Cron, Wikipedia](https://en.wikipedia.org/wiki/Cron)
- [Working with Cron, AWS](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-cron.html)
- [Cheatsheet](http://bencane.com/2012/09/03/cheat-sheet-crontab-by-example/)

**Comment by bdistin** [comment]
I know I won't add support for `@reboot` or `?`. They don't really work in our paradigm.

`@annually` will take 2 seconds to add. And using Math.random() H could be added very easily.

But L, W, and # are all going to take a significant amount of code and thought. I personally would like L and #, I am not sure about W though. These wildcards may not be added before the 1.0.0 release.

**Comment by kyranet** [comment]
For `?` we can use [minute](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMinutes), [hour](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCHours), [day](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDate), [month](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMonth), [weekly](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCDay) methods from [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) depending on the position of the wildcard. Should be easy to implement though.

Yes, we already discussed about `@reboot` not being to be implemented, that's why I didn't include it in the description.

**Comment by bdistin** [comment]
`?` would only work on the moment the cron is generated; not consistent with the reboot time (each other). If that's ok, i could add that easily too... But this structure should be independent. So no client, or passing in the client start time.

**Comment by kyranet** [comment]
You always have access to `new Date()` or `Date.now()` which return the current date or timestamp respectively. And we also do some wildcard changes, for example the pattern `'0 0 * * mon,fri'` gets stored as `'0 0 * * 1,5'` (as Sunday is 0), we can make this process and turn `'? ? * * *'` into `'8 15 * * *'` (it's 15:08 (UTC) right now), then, store the cron as that pattern instead of keeping the `?`s.

**Comment by PierreAndreis** [comment]
We could also use http://bunkat.github.io/later/

**Comment by tech6hutch** [comment]
That's certainly more understandable, for people who don't know Cron. The current system uses Cron notation, however.

**Comment by bdistin** [comment]
No plans to add this for the foreseeable future unless someone wants to take this up. Closing this issue for now.
