### ISSUE TITLE
Proposal: Better SchemaPiece options

### ISSUE THREAD

**Issue by kyranet** [dirigeants/klasa#185]
### Describe the proposal

Since SGv1, in the PR [#255](https://github.com/dirigeants/komada/pull/255) from Komada, we had the first implementation of `SchemaPiece` being able to store more than a single value of the same type (instead of being type array, from the former configuration system).

However, this system is extremely old and should be renamed and refactored into something much better, in this proposal, I'll use `SchemaPiece#multiValue` as a placeholder for a better name.

**What does `SchemaPiece#multiValue` do compared to `SchemaPiece#array`?** The current name limits the options, the values may be contained inside an array or not, but, what if I want to use `Set` or `Map`? The current system does not allow it, but multiValue will.

### Implementation

There are multiple ways to achieve this, but I'll present two in this proposal:

#### ValueController

This is more versatile, it allows custom types and moves some of the heavy work from SG to them, it also allows users to implement their own `ValueController`, for example, one being `Collection` extending `Map` and so on. Compatibility with `string` for simplicity in `SchemaFolderAddOptions` is accepted with a later resolve.

Said `ValueController` would implement basic methods such as `create`, `clone`, `add`, `remove` and `modify` and they could be stored in `GatewayDriver` together with the available key types.

---

#### Internal Resolving

This is less customizable and more hardcoded, plus makes SettingGateway's internals much heavier. These methods would be integrated in a different file (similar to a util) for later usage.

---

In both options, you'll be able to do

```javascript
SchemaFolder#add('tags', { type: 'string', multiValue: 'Map' });
```

*And the new values will be stored in the Map. However, some of the multiValue may not be able to be directly configurable, so they'll have the same behavior as `type: 'any'`: sets `SchemaPiece#configurable` to false.*

> **This proposal is not merging on [#179](https://github.com/dirigeants/klasa/pull/179) but in a later one**.

**Comment by UnseenFaith** [comment]
The example of using set in this is completely useless because Array already removes/adds by default, which is the equivalent to using new Set().
As for map you have issues:
  - what should you do about storing discord.js structures
  - what about non-discord.js structures that don't have a id value (storing a complete json is going to get pretty overkill as the map increases in size

**Comment by kyranet** [comment]
- Not quite. [`Set#has()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) is faster than most methods for Array. And there can never be two entries with the same value (like in Array) but it benefits on how easy it is to use. SettingGateway would buy an instance of `Set` instead of `Array` when the key requires a Set.
- That's an issue for `ValueController`, not for the proposal itself, although that can be handled, it's up to the developer to not do such practises.
- In case of Map, it's unaffected. Why? Because one simple fact: I cannot store hashed collections (Map/WeakMap/Set/WeakSet) into a database, I need to convert them to array first.

For example, the following Map instance:

```javascript
Map { '224236171838881792' => { colour: 'red', animal: 'dog' } }
```

Is stored into a JSON db as:

```javascript
[
    ['224236171838881792', { colour: 'red', animal: 'dog' }]
]
```

Then if you pass the array above into `new Map()`, you'll get the first map. And it does not have a property of `id`, instead, it's mapped by a key that serves as id.

**Comment by UnseenFaith** [comment]
Why can't you just do an object instead of map then
```js
{
  '224236171838881792': { somedata }
}
```

**Comment by kyranet** [comment]
Because that requires the iteration of an object's keys with [`Object.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) which performance is 27 times lower than iterating an array by index. Building so many `Configuration` instances and needing to run `Object.keys` in one or more keys in every single one of them may result on a slow startup.

Outside performance, it's a pain for TypeScript users to handle that, and it's also an antipattern, it should not be made.

**Comment by UnseenFaith** [comment]
TypeScript has no bearing on this conversation. realistically this is only going to be used by Javascript users.

It's already going to be taxing on performance and startup for having to iterate over the parsed array to create the map.

It's also going to create a new interface that will be more ambiguous compared to the other ones
```<Config>.someMapKey.get() <-- having to use a function to get the data rather then
<Config>.someObjectKey["Object"]
<Config>.someArrayKey[0]
<Config>.someString -->
```

**Comment by kyranet** [comment]
It's not taxing on performance if the array is empty, which it's the case for the 50% of cases. `new Map()` doesn't iterate the array if it's empty. Unlike your idea of an object, that needs to run an expensive function (which filters ~7 built-in properties of `Object`, so it always has keys to iterate).

Not to mention that when you add/remove a property from an object, you are rebuilding it from scratch, so, it's an incredibly bad idea, and remember that we have discussed about this in Komada 0.20.0 development. This behavior does not happen in a Map as it's a collection of key/value designed to have a variable amount of entries, which objects aren't (due to their nature of immutability).

What you're proposing is much more taxing than my proposal in both CPU and RAM, as well as it contains antipatterns that seriously affect the performance in V8, it's all based on [program optimization](https://en.wikipedia.org/wiki/Program_optimization).
