### ISSUE TITLE
Proposal: "spamProtection"property for inhibitors

### ISSUE THREAD

**Issue by pedall** [dirigeants/klasa#189]
### Describe the proposal

I think this term is very misleading for a property that is only there to prevent an inhibitor to be run for the help command. If we want it configurable for inhibitors to only be run in certain scenarios, this should be more configurable.

**Comment by bdistin** [comment]
The spamProtection option is there to prevent the inhibitor to be run in non-spamProtection scenarios. Unless you have other scenarios that should be taken into account in the core framework, and not delegated in your own bot, this proposal is meaningless.
