### ISSUE TITLE
Proposal: Modify msg.reply, for command editing

### ISSUE THREAD

**Issue by tech6hutch** [dirigeants/klasa#209]
The Message#reply method would be more useful if it supported command editing, like KlasaMessage#send, et. al., do. I am proposing that Klasa replaces that method with its own.

**Comment by MrJacz** [comment]
I suggested this a long time ago, not sure what happened about it but
```js
return this.send(content, { reply: this.member || this.author });``` is how its done and should be done

**Comment by bdistin** [comment]
This pretty much breaks a major rule of klasa, and that's `Klasa core only adds functionality to discord.js, not changes or breaks functionality of d.js.` What users do in their user space to change or break functionality of d.js, is up to them.

But it's bad enough d.js sends us any dev, where the dev states they are using klasa, even though the question is purely d.js. We don't need to validate them sending devs our way for d.js questions.
