### ISSUE TITLE
Help command on iOS

### ISSUE THREAD

**Issue by ShayBox** [dirigeants/klasa#242]
### Describe the issue

![image](https://user-images.githubusercontent.com/9505196/37639624-951c772e-2be8-11e8-9481-8f9327efd15d.png)

### Code or steps to reproduce

Use the built-in help command on iOS

### Expected an actual behavior* **Google is always right /s*

![image](https://user-images.githubusercontent.com/9505196/37639614-8b76a29e-2be8-11e8-9d67-eb2da9698eb9.png)

### Further details

- **discord.js version**: 12.0.0-dev
- **node.js version**: v9.8.0
- **Klasa version**: 0.5.0-dev
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

To fix: Add newline before starting the codeblock
Additional: Remove blank newline at end of codeblocks
![image](https://user-images.githubusercontent.com/9505196/37639722-e7b7e932-2be8-11e8-9e65-7174f3fc1fd7.png)

**Comment by bdistin** [comment]
Can you see if the latest commit fixes this? I do not have any IOS devices to confirm if my commit fixes this.

**Comment by ShayBox** [comment]
Nope 
![image](https://user-images.githubusercontent.com/9505196/37686025-1e15793a-2c6c-11e8-9f33-eba9ffe10f52.png)

**Comment by ShayBox** [comment]
I don't know why it doesn't work 🤔

**Comment by ShayBox** [comment]
I did some more testing, it is the content inside... iOS just cant handle the actual content 
![image](https://user-images.githubusercontent.com/9505196/37686967-1bb60bc4-2c70-11e8-8fa1-8a5dca356cac.png)
![image](https://user-images.githubusercontent.com/9505196/37686976-222715de-2c70-11e8-89fa-6a60139551f0.png)

**Comment by bdistin** [comment]
I don't think that is something that can be fixed on the lib side then. Probably just have to wait until hammer & chisel fixes the iOS app.

**Comment by CyberiumShadow** [comment]
This has been a long time issue since Komada.

I'm primarily on an IOS Device so I've noticed it a lot.

Given that the functionality works fine on Desktop clients and Android, all the issue lies with atm is either iOS itself or the way the code block implementation works in iOS Discord app.

**Comment by bdistin** [comment]
Closing this issue as it cannot be fixed by Klasa, it's a Hammer and Chisel bug.
