### ISSUE TITLE
Proposal: Cleaner way to change the console colors

### ISSUE THREAD

**Issue by KingDGrizzle** [dirigeants/klasa#258]
### Describe the proposal

Currently, changing the colors for the KlasaConsole is, tedious. With code like this
```js
new Client({
    console: {
        colors: {
            [event]: {
                time: {
                    background: "green",
                },
            },
        },
    },
});
```
looking quite bad.

This proposal is a way to either re-use the already existing Colors class, or another class, to be able to do something more like
```js
new Client({
    console: {
        colors: {
            [event]: {
                time: new Colors({ background: "green", text: "white", style: "underline" }),
                message: new Colors({ background: "white", text: "black" }),
            },
        },
    },
});
```

This looks way cleaner, and more concise in my opinion., and doesn't go extremely deep in the client options. (something eslint will appreciate if you have the depth rule configured.)

In the given example, `[event]` is an actual event name, like `log` or `warn`

**Comment by bdistin** [comment]
As explained in chat, this is no different than how it is currently, but with the added requirement `new Colors()` (aka more verbose), and restricts you from configuring those options in a .json file, as you normally would.
