### ISSUE TITLE
Proposal: Default extendables' appliesTo to extendables/subfolder

### ISSUE THREAD

**Issue by tech6hutch** [dirigeants/klasa#267]
### Describe the proposal

When you have many extendables, for different classes, I bet it gets pretty disorganized. You can prefix their filenames with the class name, e.g., userProfile.js, but then you have to explicitly specify the property/method name in each one.

I'm proposing that subfolders in the `./extendables/` folder be used as the appliesTo arg by default, so that users can then make the filename the name of the property/method, for simplicity and for better organization.

#### Rationale

Commands have categories, which are useful for file organization. I propose similar usefulness for extendables.

### Code or steps to use

`./extendables/User/profile.js`:
```js
const { Extendable } = require('klasa');

class MyExtendable extends Extendable {

    get extend() {
        // return whatever
    }

}

module.exports = MyExtendable;
```

A file that uses it:
```js
msg.author.profile // etc.
```

### Caveats

- You wouldn't be able to specify multiple classes to apply the extendable to
  - You can still explicitly use the `appliesTo` arg
  - How often do users use multiple classes in appliesTo, anyway?
- You could do something unintuitive, like have a file `./extendables/User/modLog.js`, with `appliesTo: ['Guild']`
  - That's your problem, to be honest; you can already do unintuitive things
- Unlike command categories, extendable appliesTo can be set explicitly with an option; this makes for an inconsistency in Klasa
- For a class that one has a lot of extenders for, it probably makes more sense to make a class extending it and pass that to Discord.js directly, rather than using Klasa extendables

**Comment by Dev-Yukine** [comment]
+1 to this idea, makes it way more organizied and this should be easy to implement since klasa kinda does something simular to command folder

**Comment by UnseenFaith** [comment]
If this idea is implemented, it should be moved to the base class, and all of the pieces should inherit it, regardless of whether they use it or not.

**Comment by tech6hutch** [comment]
Would subfolder just be ignored if they don't use it?

**Comment by tech6hutch** [comment]
Edit: I thought of another caveat

**Comment by UnseenFaith** [comment]
Every piece could have a subfolder property (similar to category/subcategory in commands) in which would contain the location of the piece. Every piece would have it assigned to variable its suppose to be or null, and then can be used in the piece that it might be needed in, i.e. for appliesTo.

Issues I could see with this:
 - Performance drops for having to read extra dirs that may or may not be empty. (All other pieces beside commands to my knowledge only read the top dir).
 - Pieces that require specific subfolder names would error.

**Comment by tech6hutch** [comment]
Fair point, but what do you mean by "Pieces that require specific subfolder names would error"?

**Comment by UnseenFaith** [comment]
So like if you want to have a User extendables folder, and you incorrectly spelled User or anything that would make it not "User" when you try to apply it, it would fail.

**Comment by kyranet** [comment]
Your proposal lacks of a little detail: the option `klasa` from [ExtendableOptions](https://klasa.js.org/#/docs/main/master/typedef/ExtendableOptions).

**Comment by Soumil07** [comment]
I like this. IMO the klasa ones should go into a subcategory called klasa and have an appliesTo arg regardless.

**Comment by tech6hutch** [comment]
Jacz suggested that, too. `./extendables/klasa/KlasaUser/profile.js`

**Comment by tech6hutch** [comment]
Oh, I misunderstood you. That would work, too.

**Comment by bdistin** [comment]
No, while you can already organize pieces into subfolders, it's not really fitting to make that have meaning here.
