### ISSUE TITLE
Help command breaks with too many commands in a category

### ISSUE THREAD

**Issue by Dev-Yukine** [dirigeants/klasa#269]
### Describe the issue
If your category has over a certain amount of commands (54 in my case) the default help commands breaks due to not correctly splitting the codeblocks (the .send() catch fires with a wrong message)
### Code or steps to reproduce

1. create a category with a lot of commands
2. try to use the help command

### Expected an actual behaviour
show help command correctly

### Further details

- **discord.js version**: https://github.com/discordjs/discord.js/commit/f2474845ba804c19313669e5f9405a7298352f7d [Newest Master]
- **node.js version**: 9.11.1
- **Klasa version**: https://github.com/dirigeants/klasa/commit/db946cc8c3667a916544a001f00ed45af740e12b
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: https://github.com/dirigeants/klasa/commit/db946cc8c3667a916544a001f00ed45af740e12b

**Comment by Kashalls** [comment]
How about pages for the categories?

**Comment by QuantumlyTangled** [comment]
Yes like a rich display. If needed I have one made already

**Comment by kyranet** [comment]
@QuantumlyTangled RichDisplays require extra permissions and uses embeds, that's definitely not going to be in core but for klasa-pieces. This issue is for the core help.

**Comment by Kashalls** [comment]
I don't see any logical ways to do this with out making it "too" complex. You may have to limit a certain amount of characters to a description which may suck.

**Comment by TheFloppyBanana** [comment]
What if splitting it by text limit, just split it per command category?

**Comment by bdistin** [comment]
It's split on category now to maintain formatting. So it wouldn't matter if you limited the description characters, you would always be able to add so many commands to a single category it would break. Then again, so long as you keep your commands "well categorized", it will never break no matter how many commands you have in your bot. So...  ¯\\\_(ツ)\_/¯

**Comment by tjrgg** [comment]
With the core help command, you can get more details for each command, IIRC. What if you removed the description in the main command list if there are too many commands and instead put the command to use to get more information?

**Comment by bdistin** [comment]
It doesn't matter, no matter how little information you pass, there is always a point where you have too many commands that make the chunks bigger than the 2k char limit.

**Comment by Anish-Shobith** [comment]
I would like to extend @Kashalls idea 
So basically it would be simple 
when user type the help command it would list all the categories not the commands 
example : 
![image](https://user-images.githubusercontent.com/38991749/54068220-63399800-4270-11e9-98c3-c5f3e67e68c0.png)
Then to view the commands category wise they would have to do `<prefix> help <category>`
but you would say it would still break if they are over 2k characters ...
why not paginate this 
like if they are over 10 commands then it would automatically paginate!! well i don't have any example for this but to be honest this would work like first display categories then commands via pagination
Let me know what you guys have to say!! you can ask me on discord too i am in server 
Anish Shobith -username

**Comment by bdistin** [comment]
Closing as this is a known issue, and no real solution has been learned in the last year. This issue has exceeded its usefulness.
