### ISSUE TITLE
Conf command breaks when having a piece in a SchemaFolder

### ISSUE THREAD

**Issue by TheFloppyBanana** [dirigeants/klasa#270]
### Describe the issue
Having SchemaPiece on a SchemaFolder breaks `conf get` when trying to access the folder, `conf get SchemaFolder#SchemaPiece` will work just as fine.
### Code or steps to reproduce

1. Create a SchemaFolder
2. Create a SchemaPiece with `type` as `TextChannel`
3. Run `conf get <SchemaFolder>`

### Expected an actual behaviour
- show the SchemaFolder with the piece properly

### Further details

- **discord.js version**: [discordjs/discord.js@4ab72af](https://github.com/discordjs/discord.js/pull/2330/commits/4ab72afac0fa714653cfe27b9d175c22a2ae5fd4)
- **node.js version**: v9.2.1
- **Klasa version**: [db946cc](github:dirigeants/klasa#db946cc8c3667a916544a001f00ed45af740e12b)
- [ ] I have modified core files.
- [X] I have tested the issue on latest master. Commit hash: [db946cc](github:dirigeants/klasa#db946cc8c3667a916544a001f00ed45af740e12b)

**Comment by Soumil07** [comment]
This is because conf get is supposed to be for *keys* not folders. Think of the default list as a folder too (just conf list). You can't use conf get without any args and expect it to behave like list. Similarly, when accessing a folder, list is the only way to do it. `conf list SchemaFolder`.

**Comment by UnseenFaith** [comment]
That doesn't take away from the fact that `conf get SchemaFolder` should behave like every other key. If it's a folder it should resort to listing it out. Ideally `list` and `get` should be merged into one single command since they're pretty much identical.

**Comment by TheFloppyBanana** [comment]
> That doesn't take away from the fact that `conf get SchemaFolder` should behave like every other key. If it's a folder it should resort to listing it out. Ideally `list` and `get` should be merged into one single command since they're pretty much identical.

I like @UnseenFaith's idea, anyways thank you for both of your answers! <3
