### ISSUE TITLE
Proposal: Increment method for SG

### ISSUE THREAD

**Issue by gc** [dirigeants/klasa#296]
An increment method for SG to add/remove numbers from SG Configs.:
```js
// Increment by 1
this.client.configs.increment('commandsUsed', 1);
// Decrement by 1
this.client.configs.increment('commandsUsed', -1);
```

Current Method of doing this:
```js
// Increment by 1
this.client.configs.update('commandsUsed', this.client.configs.commandsUsed + 1);
// Decrement by 1
this.client.configs.update('commandsUsed', this.client.configs.commandsUsed - 1);
```

Databases have built-in methods for incrementing which might help in implementing this in providers. [MongoDB](https://docs.mongodb.com/manual/reference/operator/update/inc/)
[RethinkDB](https://www.rethinkdb.com/api/javascript/update/)

Benefits: Shorter and simpler. Perhaps faster?
Use cases: experience systems, analytics and counters.

**Comment by MrJacz** [comment]
Well you dont increment when you decrease, so call it something like tha

**Comment by tech6hutch** [comment]
Night as well make helper functions for other common math operations as well, maybe object/array methods etc.

**Comment by MrJacz** [comment]
actually, this could be an option in the `update` method.
like we have `action` it could be `{ action: "increment" }` for increase and `{ action: "decrease" }` for decrease instead of creating a new method

**Comment by gc** [comment]
The method im suggesting is following [the way MongoDB does it](https://docs.mongodb.com/manual/reference/operator/update/inc/), you increment by a negative number to decrement, which is simpler, and makes sense because `10 + -2 === 8`.  Secondly, having to type out an object with an action key defeats half the purpose of it being shorter and simpler.

**Comment by Tylertron1998** [comment]
While I don't believe this belongs in core, I think that a PR to pieces for something like this would be nice; an extendable for various helper functions.

**Comment by bdistin** [comment]
I agree with Tyler here, it would make a great extendable for the [pieces repo](https://github.com/dirigeants/klasa-pieces), but doesn't really belong in the core framework, as SG is already quite much...
