### ISSUE TITLE
[1.0.0 Roadmap] Remove all SQL state from the library (and schema).

### ISSUE THREAD

**Issue by kyranet** [dirigeants/klasa#311]
The library should not care anything about what the provider is using in the background. This also allows for each sql provider to be more customized to that individual database, rather than trying to find a set of sql syntax/types common to all sql databases. As well as reduction of core code (bloat) and finally massive simplification of SettingGateway.

Potentially add a SQL QueryBuilder Util with overridable defaults, to aid in reduction of duplicate code/making SQL Providers more maintainable.

**Comment by bdistin** [comment]
There is already a pr for this, this doesn't need an issue made.
