### ISSUE TITLE
Proposal: Add an array of wanted ids to be requested in Provider#getAll

### ISSUE THREAD

**Issue by KingDGrizzle** [dirigeants/klasa#328]
### Describe the proposal

Currently Provider#getAll wants just the table, and expects to return all the data. That is horrible, because that means you could potentially be fetching thousands of documents for no apparent reason. (not to mention in https://github.com/dirigeants/klasa/blob/60c8503bd8ba741e2ed9101864f79ede1bb7eb39/src/lib/settings/Gateway.js#L185-L198 it fetches all data so you also have never used data cached in your shards)

This proposal suggests adding an optional array of ids to the getAll functions, where each provider has to handle it manually (most databases have ways of doing this. Mongo has $in, most of sql seems to have `select item from table where item.id in (values, here)`, rethink can do filtering, etc.)

### Example Code

```js
async getAll(table, filter = undefined) {
    if (util.isArray(filter)) {
        // Fetch data based on the filter, where each item in filter is the id
        // for instance, assuming we have sql
        return this.run(`SELECT * FROM ${table} AS g WHERE g.id IN (${filter.join(",")})`)
    }
    // Fetch all data like normal
}
```

### Expected and actual behaviour
This should return all data if no array is provided, or filtered data otherwise. This should NOT have to fetch all data and return the correct one, but should rather integrate with the database's syntax and fetch exactly whats needed at once.

### Further details

- **discord.js version**: not relevant
- **node.js version**: not relevant
- **Klasa version**: 0.5.0-dev
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
Support for this landed for RethinkDB and RebirthDB, looking forward to contributors to help us with the rest of providers before doing the change. As this is high priority, we'll offer support to our contributors to efficiently implement this feature, so we can land a fix for this.

**Comment by Dinnerb0ne** [comment]
A limit parameter can also be added, to limit the number of results.

**Comment by kyranet** [comment]
They're already limited by the length of the array.

**Comment by kyranet** [comment]
Fixed in https://github.com/dirigeants/klasa-pieces/pull/67
