### ISSUE TITLE
Unable To Edit Database With Latest Klasa

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#345]
### Describe the issue
In the latest Klasa, it has broken working with our database completely. Whenever we try to save something using SG it would save it only in the cache. After rebooting all changes would become reverted. After much testing, it was discovered that this only occurs when updating to latest klasa.

### Code or steps to reproduce

```js
1. Update to latest klasa
2. Try to work with SG to save things like editing the prefix

```

### Expected and actual behaviour

Save into the database as well as the cache so that rebooting bot does not delete all data changed.

### Further details

- **discord.js version**: master
- **node.js version**: 10.1
- **Klasa version**: master
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:

**Comment by bdistin** [comment]
Can you provide @kyranet with some example code from your bot. I am sure that will be needed, since I am not aware of any issues like that, and I should be using latest master. (I need to check)
