### ISSUE TITLE
Feature Request: Caching

### ISSUE THREAD

**Issue by Soumil07** [dirigeants/klasa#347]
### Describe your proposal
Currently, caching in the SettingGateway is done through DiscordJS Collections. There should be an option to add optional caching providers, such as Redis. I see this as adding it to the Provider constructor:

```js
constructor(...args) {
  super(...args, { cache: true });
}
```

### Usecases for your proposal
Better caching for large bots, where the huge caches can affect memory.

**Comment by AdityaTD** [comment]
I actually like this idea, if it can be implemented then I'd surely use Redis for caching while RethinkDB as my main data provider.

**Comment by bdistin** [comment]
This was done before in a much earlier version, and it actually had the opposite result (killed speed, increased CPU load, and memory). This even being an "option" kills Klasa as an option for any large bots, so this is not feasible by design.
