### ISSUE TITLE
Proposal: Run inhibitors after running prompts, or add a new kind of inhibitors

### ISSUE THREAD

**Issue by KingDGrizzle** [dirigeants/klasa#348]
### Describe your proposal

Currently you can only inhibit a command before getting its arguments, to check things like if the command is nsfw and so is the channel. (pure example)

This proposal would add a way for inhibitors to either be ran after running the message prompter, so you can also check for flags or arguments.

### Use cases for your proposal

If you want to forbid a command for running due to an argument being bad (say, filter bad words from a command), this would allow you to do so.

### Expected and actual behavior

Expected:
Inhibitors can run after the prompter, so that we can filter out anything, or a new tipe of inhibitors can appear, just like spamProtection ones

Actual:
Inhibitors run before the prompter, making them useless right now if you want to check for arguments or flags, unless you modify commandHandler.js

**Comment by Dev-Yukine** [comment]
+1 on this

**Comment by QuantumlyTangled** [comment]
Could this not be achieved by having either a custom string arguement with a filter in it or a custom arguement for that one command?

**Comment by Dev-Yukine** [comment]
thats more like a "hacky" workaround. to inhib a command you **should** use an inhibitor.

**Comment by Soumil07** [comment]
+1

**Comment by UnseenFaith** [comment]
I think it's better to implement it just calling inhibitors.run() yourself. Seems unnecessary to add extra load to the prompters that not everyone is going to want or use.

**Comment by bdistin** [comment]
Resolving arguments into parameters is expensive, more expensive than checking permissions or NSFW status of a channel. Additionally, you wouldn't want to prompt and prompt, then get told sorry you don't have permission to use this command. These and other reasons are why inhibitors **must** be before argument resolution.

As a framework, we will not run inhibitors both before and after argument resolution. You are free to do that in your own code, however.

The idea of "stage 2" inhibitors (a separate piece store) is also above and beyond what should be included with the base framework. Again, you have all the tools needed to do this in your own code.
