### ISSUE TITLE
Separate requiredPermissions For Servers And DMs

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#349]
### Describe your proposal
I would like to see if it is possible to make an klasa in built method of having separate requiredPermissions for each command. Currently, setting a requiredPermission can and will break that command on all DM just because you required a perm like manage messages.

As an example, I added a cool upgrade enhancement to the help command on my bot. However, this broke the entire help command on DM.

It would be really cool to have separate permission settings for DMs because just enhancing a bot's command should not disable it.

Essentially, make requiredPermission be unobtrusive to DMs similar to unobtrusive javascript coding on web dev. If someone(server) has the permission they have a better experience, else (dm) they use it without the improved version.

### Usecases for your proposal
Setting any command to require a perm will break it in DM, depending on the perm you require. A command should not be forcibly prohibited by default.

### Expected and actual behaviour
Even if the bot does not have Manage Messages in a DM the command should still work.

**Actual Behavior:** 
![image](https://user-images.githubusercontent.com/23035000/41729951-91ba37ac-7548-11e8-8ec3-0832f221ccab.png)

### Further details
To be honest, this is a simple workaround on the missingBotInhibitor but I still think it could be a nice enhancement to klasa to have these separate by default.

<3

**Comment by bdistin** [comment]
If we don't inhibit the command, discord api will reject your request. You can't have Manage Messages in DMs under any circumstance.
