### ISSUE TITLE
Default json provider not caching externally populated files

### ISSUE THREAD

**Issue by stensch** [dirigeants/klasa#361]
### Describe the issue
After registering a new gateway I populated it externally. I ran into problem with the default json provider, where it would not cache the files. Changing the provider to .ie sqlite and adding a field to the database (still externally) worked as expected, so it is a problem with json only as far as I can tell.

### Code or steps to reproduce

my gateway:
```js
client.gateways.register('items', {
    type: 'Folder',
	name: {
		type: 'string',
        configurable: false
	},
	price: {
		type: 'string',
        configurable: false
	}
}, { provider: 'json' });
```
I populated folder ...\bwd\provider\json\items
with:
1.json
2.json
3.json
...

Example of 1.json
```json
{"id":"1","name":"testitem1","price":"75"}
```

### Expected and actual behaviour
ev this.client.gateways expected result:
```
  items:
   Gateway {
     schema:
      SchemaFolder {
        name: [Object],
        price: [Object],
     ready: true,
     store: [Circular],
     cache: Collection {
        '1' => [Object],
        '2' => [Object],
        '3' => [Object] },
        ....
     syncQueue: Collection {} } }
```

actual result:
```
  items:
   Gateway {
     schema:
      SchemaFolder {
        name: [Object],
        price: [Object],
     ready: true,
     store: [Circular],
     cache: Collection {},
     syncQueue: Collection {} } }
```

### Further details
As a hack I managed to fix it by changing in /src/lib/settings/Gateway.js
```js
    async sync(input = [...this.cache.keys()]) {
        if (Array.isArray(input)) {
            if (!this._synced) this._synced = true;
            const entries = await this.provider.getAll(this.type, input);
    ...
```
to
```js
    async sync(input = [...this.cache.keys()]) {
        if (Array.isArray(input)) {
            if (!this._synced) this._synced = true;
            let entries;
            if (input != '') {
                entries = await this.provider.getAll(this.type, input);
            } else {
                entries = await this.provider.getAll(this.type);
            }
    ...
```

- **discord.js version**: github:discordjs/discord.js#7d2744be89f90fa16b77b6fbad95902e26f4564a
- **Klasa version**: github:dirigeants/klasa#d80499936ef379c3dcc1f18bac7bdb7776f5b0b7

**Comment by UnseenFaith** [comment]
Functionality of only downloading what is needed breaks every custom gateway that doesn't have a way of providing some sort of cache before syncing. This should probably be fixed on Klasa's side to download everything if there's no way to determine what is and what isn't needed, rather than leaving an empty cache and having user polyfill with fetch calls.

/cc @kyranet
