### ISSUE TITLE
Cannot read property '_existsInDB' of undefined (client.gateways.register)

### ISSUE THREAD

**Issue by Lovinity** [dirigeants/klasa#414]
### Describe the issue
When attempting to register a new gateway in Klasa 0.5-dev (latest commit as of this posting), an error is thrown:

[2018-09-02 23:02:39] [EVENT] /root/omshanti/node_modules/klasa/src/events/onceReady.js
[2018-09-02 23:02:39] TypeError: Cannot read property '_existsInDB' of undefined
[2018-09-02 23:02:39]     at Gateway.sync (/root/omshanti/node_modules/klasa/src/lib/settings/Gateway.js:102:24)
[2018-09-02 23:02:39]     at <anonymous>

### Code or steps to reproduce
main.js
```js
const {Client, PermissionLevels, Schema} = require('klasa');
const config = require('./config.js');

// Prepare Klasa
const client = new Client({
    clientOptions: {
        fetchAllMembers: false
    },
    prefix: '!',
    cmdEditing: true,
    typing: true,
    providers: {
        default: 'rethinkdb',
        rethinkdb: {
            pool: true,
            servers: [{host: 'localhost', port: 28015}]
        }
    },
    gateways: {
        guilds: {
            schema: new Schema()
                    .add('prefix', 'string')
                    .add('language', 'language')
                    .add('disableNaturalPrefix', 'boolean')
                    .add('disabledCommands', 'command', {
                        array: true,
                        filter: (client, command, piece, language) => {
                            if (client.commands.get(command).guarded)
                                throw language.get('COMMAND_CONF_GUARDED', command);
                        }
                    })
                    .add('botChannel', 'textchannel')
                    .add('modLogChannel', 'textchannel')
                    .add('iceBreakerChannel', 'textchannel')
                    .add('noSelfModRole', 'role')
                    .add('muteRole', 'role')
                    .add('conflictResolutionMembers', 'integer', {default: 3})
                    .add('conflictResolutionTime', 'integer', {default: 15})
                    .add('verifiedRole', 'role')
                    .add('guildTasks', 'string', {configurable: false})
                    .add('reportMembers', 'integer', {default: 3})
                    .add('reportTime', 'integer', {default: 60})
                    .add('pendSuspensions', 'any', {array: true, configurable: false})
                    .add('pendBans', 'any', {array: true, configurable: false})
                    .add('pendIncidents', 'any', {array: true, configurable: false})
                    .add('incidentsCategory', 'categorychannel')
                    .add('staffCategory', 'categorychannel')
                    .add('antispamCooldown', 'integer', {default: 50})
                    .add('antispamLessStrictRoles', 'role', {array: true})
                    .add('antispamLessStrictChannels', 'role', {array: true})
        },
        users: {
            schema: new Schema()
                    .add('guilds', 'any', {array: true, configurable: false})
        }
    },
    // Add custom permissions
    permissionLevels: new PermissionLevels()
            // everyone can use these commands
            .add(0, () => true)
            // Members can view audit logs
            .add(4, (client, message) => message.guild && message.member.permissions.has('VIEW_AUDIT_LOG'), {fetch: true})
            // Members of guilds must have 'MANAGE_GUILD' permission
            .add(6, (client, message) => message.guild && message.member.permissions.has('MANAGE_GUILD'), {fetch: true})
            // The member using this command must be the guild owner
            .add(7, (client, message) => message.guild && message.member === message.guild.owner, {fetch: true})
            // Bot owner
            .add(9, (client, message) => message.author === client.owner, {break: true})
            // Allows the bot owner to use Bot Owner only commands, which silently fail for other users.
            .add(10, (client, message) => message.author === client.owner),
    readyMessage: (client) => `${client.user.tag}, Ready to serve ${client.guilds.size} guilds and ${client.users.size} users`
});

// Add a channels gateway
client.gateways.register('channels', {
    provider: 'rethinkdb',
    schema: new Schema()
            .add('conflictResolution', 'string', {array: true})
});

client.login(config.botToken);
```

### Expected and actual behavior

I expect that the channels gateway is registered at client.gateways.channels, which I can then extendable to TextChannels. This used to work at commit a444a80, but was broken as of commit 9b15f1a (issue #383 )
### Further details

- **discord.js version**: master (75745fe)
- **node.js version**: 8.11.4
- **Klasa version**: master (7c6010a)
- [ ] I have modified core files.
- [X] I have tested the issue on latest master. Commit hash: 7c6010a

**Comment by Tylertron1998** [comment]
I believe the correct way to change the Schema for Guilds/Users is by calling Schema#add on the static Client - as follows:
```js
Client.defaultGuildSchema.add(...);
Client.defaultUserSchema.add(...);
```

Have you tried doing it this way?

**Comment by Lovinity** [comment]
Further clarity since I was vague:

@Tylertron1998 I tried what you suggested. It made no difference. I originally was modifying the schema via client options because I planned one of the things I was going to do with the bot might necessitate a change in the original schema (opposed to just adding). However, since I have not reached that point yet, I switched to using the documented way of adding to the default schema. The error still exists.

When removing the client.gateways.register portion of main.js, the bot fully loads and works (apart from anything requiring the channels settings). When trying to register the channels gateway, the error specified spits out and the bot fails to fully load.

**Comment by bdistin** [comment]
This is @kyranet 's field, but guessing not all channels you have Setting's instances on them. You say TextChannels, but in reality all channels must include `.settings`

**Comment by Lovinity** [comment]
I thought since this is not a default gateway, it would not become a property of channels by default; I would have to use an extendable. My plan was to use an extendable on TextChannels; this would only be for text channels.

**Comment by Tylertron1998** [comment]
@Lovinity the problem is - the channels don't have a settings instance. What you need to do is use discord.js' Structures.extend method, to add these in, as so:
```javascript
const { Structures } = require('discord.js');

Structures.extend('TextChannel', TextChannel => {
	class MyTextChannel extends TextChannel {

		constructor(...args) {
			super(...args);

			this.settings = this.client.gateways.channels.get(this.id, true);
		}

	}

	return MyTextChannel;
});

Structures.extend('CategoryChannel', CatagoryChannel => {
	class MyCatagoryChannel extends CatagoryChannel {

		constructor(...args) {
			super(...args);

			this.settings = this.client.gateways.channels.get(this.id, true);
		}

	}

	return MyCatagoryChannel;
});

Structures.extend('VoiceChannel', VoiceChannel => {
	class MyVoiceChannel extends VoiceChannel {

		constructor(...args) {
			super(...args);

			this.settings = this.client.gateways.channels.get(this.id, true);
		}

	}

	return MyVoiceChannel;
});

Structures.extend('GuildChannel', GuildChannel => {
	class MyGuildChannel extends GuildChannel {

		constructor(...args) {
			super(...args);

			this.settings = this.client.gateways.channels.get(this.id, true);
		}

	}

	return MyGuildChannel;
});
```
Then, simply require this file, and it should be good to go. I've just tested it myself, and haven't ran into any issues.

**Comment by Lovinity** [comment]
@Tylertron1998 I think we're having a miscommunication. The issue is not extending it to channels.settings... I can do that with an extendable just like I did guildMember.settings . My issue is the channels gateway is not registering because of the error in my initial post. Since it's not registering, I can't do anything with it; this.client.gateways.channels does not exist.

**Comment by Lovinity** [comment]
Structures.extend with this.settings stopped working for me on recent Klasa commits; I have to use extendables now. Structures.extend always errors TypeError: Cannot set property settings of [object Object] which has only a getter .

My extendable looks like this:
```js
const {Extendable} = require('klasa');

module.exports = class extends Extendable {

    constructor(...args) {
        super(...args, {appliesTo: ['TextChannel'], name: 'settings'});
    }

    get extend() {
        return this.client.gateways.channels.get(`${this.guild.id}-${this.id}`, true);
    }

};
```

The extendable isn't the issue though; even removing the extendable does nothing... I still get the error when trying to register the channels gateway.

**Comment by UnseenFaith** [comment]
That extendable only applies to TextChannel. Regardless of whether you believe that the extendable isn't or is the issue, starting at the first comment of this issue, the problem at hand is that there are entries in your cache (in this case, client.channels) do not have a `settings` property. To properly work on channels, you will need to extend every possible channel type that could be cached in client.channels (TextChannel, VoiceChannel, CategoryChannel, etc..).

**Comment by Lovinity** [comment]
Ah, I understand now. I apologize. It is now working, thank you.

**Comment by UnseenFaith** [comment]
No problem.
