### ISSUE TITLE
RichDisplay Breaks For Users When They Dont Have Read Message History

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#415]
### Describe the issue
What does RichDisplay have to do with Read Message History? RD is not extended.

I had this issue with users reporting they were unable to change pages on this 1 specific channel on this 1 specific server and after a lot of testing and checking we figured out the cause of it was that users did not have Read Message History. When enabling this they seemed to be able to flip pages. 

### Code or steps to reproduce

```js
1) Create a rich display with multiple pages on a channel where USERS do not have the ability to Read Message History. The bot does have permission.
2) Have the user open the channel and use the rich display
3) Have the user tap a reaction
```

### Expected and actual behavior
Expected: The user is able to flip pages even without any need for Read Message History permission.
Actual: Users are not able to flip pages. Tapping a reaction does nothing on the RD.

### Further details

- **discord.js version**: github:discordjs/discord.js#6841b4e66a9783c731ab2bf1b1bee2090b6a140d
- **node.js version**: 10.9
- **Klasa version**: github:dirigeants/klasa#5a0ea292f0c8d522b26202a111445a234b53a87d
- [ ] I have modified core files.: Some files are transferred/extended but not RichDisplay
- [x] I have tested the issue on latest master. Commit hash:

**Comment by Soumil07** [comment]
This is more likely a Discord API issue - upon further testing I saw Discord doesn't emit the MESSAGE_REACTION_ADD event on messages if the user doesn't have Read Message History permissions.

**Comment by bdistin** [comment]
https://discordapp.com/developers/docs/resources/channel#create-reaction

>Create a reaction for the message. This endpoint requires the 'READ_MESSAGE_HISTORY' permission to be present on the current user. Additionally, if nobody else has reacted to the message using this emoji, this endpoint requires the 'ADD_REACTIONS' permission to be present on the current user.
