### ISSUE TITLE
Enable requiredSettings For Non-Guild Gateways

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#435]
### Describe your proposal
Currently, `requiredSettings` property will only work for settings in the guild schema. There is no way to make sure that this user has this setting in the user or member settings. It is always assumed that the setting required to run the command is a guild setting.

### Use-Cases for your proposal
Add checks for settings from the member settings for member gateways.

### Expected and actual behavior
Currently, Klasa assumes that a setting that is required MUST be a guild setting. Non-guild settings will throw and cancel the commands usage if a member setting is added in when using the member gateway.

### Further details
Maybe if this wasn't an array of strings but tuples.
```js
requiredSettings: [
	['guild', 'settingName'], 
	['member', 'settingName'], 
	['author', 'settingName']
],
```
If the proposal is approved:

https://github.com/Skillz4Killz/klasa/pull/4/files

**Comment by UnseenFaith** [comment]
```js
requiredSettings: {
  guild: ['setting1', 'setting2'],
  member: ['setting3, 'setting4],
  user: ['setting5, 'setting6]
}
```
Would probably make more sense.

**Comment by Skillz4Killz** [comment]
Would that not increase the number of loops you will need? Any better alternative you can suggest then what I made below?

```js
const keys = Object.keys(command.requiredSettings);
const settingsToCheck = [];

for (const key of keys) {
	for (const setting of command.requireSettings[key]) settingsToCheck.push([key, setting]);
}

const requiredSettings = settingsToCheck.filter(setting => message[setting[0]].settings.get(setting[1]) == null);

if (requiredSettings.length) throw message.language.get('INHIBITOR_REQUIRED_SETTINGS', requiredSettings);
```
