### ISSUE TITLE
SettingsGateway doc "async function()" => SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by j2l** [dirigeants/klasa#484]
Since https://discord.gg/FpEFSyY is down

### Describe the issue
Following the [docs](https://klasa.js.org/#/docs/klasa/stable/Tutorials/UnderstandingSettingGateway), I get
```
SyntaxError: Unexpected token (
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[nodemon] app crashed - waiting for file changes before starting..
```
### Code or steps to reproduce
add the async function after the login:
```
client.login(token);
async function() {
  if (!client.settings.guilds.schema.modlog) {
    await client.settings.guilds.add("modlog", { type: "TextChannel" });
  }
}
```

### Expected and actual behavior
Works

### Further details

- **discord.js version**: 0.12
- **node.js version**: 8.12
- **Klasa version**: 0.5
- [ ] I have modified core files.
- [x ] I have tested the issue on latest master. Commit hash:
how?

**Comment by kyranet** [comment]
To join our official guild: ![](https://vgy.me/WnV48q.gif)

**Comment by tech6hutch** [comment]
Don't use the stable branch. It...isn't stable.

The stable docs are syntactically wrong, in this case. If you declare a function (async or not), you have to give it a name.

**Comment by j2l** [comment]
NoScript blocked klasa.me, so I got an empty popup!
I'm using    
```
"dependencies": {
    "discord.js": "github:discordjs/discord.js",
    "express": "^4.16.3",
    "klasa": "github:dirigeants/klasa",
```
I also tried adding the function a name:
```
async function addSettings() {
  if (!client.settings.guilds.schema.modlog) {
    await client.settings.guilds.add("modlog", { type: "TextChannel" });
  }
}
addSettings();
```

 and got:
```
(node:6460) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'guilds' of null
    at addSettings (E:\Downloads\klas-a\server.js:46:24)
    at Object.<anonymous> (E:\Downloads\klas-a\server.js:50:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:6460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

How to add/fill user settings?

**Comment by kyranet** [comment]
You're reading stable docs, `client.settings` was renamed to `client.gateways`.
I have created an invite link for you, expires after 1 day or 1 usage: https://discord.gg/CgJ86P

**Comment by bdistin** [comment]
Issues are not for support, if you want support please join the support guild, even if that means you have to temporarily disable no-script to get there.
