### ISSUE TITLE
Add Multi-Lingual Functionality To Command Properties

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#492]
### Describe your proposal
Klasa is great at outputting multi-lingual but very lacking in receiving multi-lingual input.

When u have string literals whether optional, mandatory or subcommands and u have the bot translated for another language like chinese that is really bad. Those foreign keyboards dont have these characters and thats bad user experience. I need a way to get `message` in the usage and other properties if possible.

Message should also be able to be passed into aliases because then aliases can be translated and you can allow commands to be run in other languages. 

### Use-Cases for your proposal
Let's take the help command as an example. For a non-english speaker they may have no idea what help even is. For them the command should run with .ayuda

This problem amplifies significantly when you reach an audience that does not use the normal alphanumeric keys and thereby their keyboard is impossible to allow bot interaction.

```js
aliases: language => language.get('HELP_COMMAND_ALIASES'),
```

```js
usage: language => `${language.get('X_COMMAND_SUBCOMMANDS')} [abc:str]`
```

### Expected and actual behavior
Expected: Able to pass in language to aliases and usage

Actual: unable to pass in language

**Comment by bdistin** [comment]
Usage and aliases are dealt with far before a single message is received, there is no way for what you propose to work.
