### ISSUE TITLE
Klasa Should Support Embeds By Default

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#494]
### Describe the issue
Embeds are a core part to so many bots. It does not make sense to not support a core feature in a discord bot. One of the biggest pain points I have all the time is caused by Klasa never supporting embeds enough. As a developer of a discord bot where embeds are almost everyday tools Klasa should by default support embed usage.

If I as a Klasa user want to use embeds and have consistency across my entire bot of its responses, I have to transfer the entirety of Klasa and maintain every line of code whenever something updates in Klasa. That's just really bad when embeds are such a core part of so many bots. Lack of supporting embeds is actually really frustrating to probably a majority of users that use klasa.

Let's take an example of the `permissions` inhibitor.

By default, this does not support embeds and will respond in a normal message format in case it errors. As a Klasa user, if I want to keep consistency in my bot's responses and send an embed I have to transfer and maintain this for all future updates. This applies to almost every part of Klasa that sends a message because embeds are not supported.

Each piece should contain a property that by default can be

```js
constructor(...args) {
        super(...args, {
            name: 'myInhibitorName',
            enabled: true,
            spamProtection: false,
			useEmbed: this.client.options.useEmbeds
        });
    }
```

Then in the code
```js
const { Inhibitor } = require('klasa');
const { MessageEmbed } = require('discord.js');

module.exports = class extends Inhibitor {

	async run(message, command) {
		const { broke, permission } = await this.client.permissionLevels.run(message, command.permissionLevel);
		if (!permission) {
			const errorMessage = message.language.get('INHIBITOR_PERMISSIONS');
			const response = this.useEmbed && message.embedable ?  
				new MessageEmbed().setDescription(errorMessage) 
				: message.language.get('INHIBITOR_PERMISSIONS');

			throw broke ? response : true;
		}
	}

};
```

Note: My method may not be the best way to accomplish this but it is a possible way that proves that Klasa can be flexible in supporting it and ideally should find the best course of action to support it.

**Summary:** Klasa should never force a user to do one or the other but allow the ability for any user to use Klasa for their needs. Klasa should always remain in a neutral corner as flexible as possible giving the users the best tool possible to work with.

### Further details

- **discord.js version**: master
- **node.js version**: 10.4
- **Klasa version**: master
- [x] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by UnseenFaith** [comment]
That doesn't really solve the issue at hand. You'd still have to transfer all of the files where you might want to change certain features of the embed.

**Comment by tech6hutch** [comment]
I like the idea of being able to easily customize Klasa's messages. A simple boolean is much insufficient for this however, imo.

Also I question the wisdom of using embeds absolutely everywhere, but I suppose it's good for consistency, and that's a separate issue from whether Klasa should support it.

**Comment by UnseenFaith** [comment]
A more coherent way of doing this would be to make language files return a new MessageEmbed() and have Klasa send that.

**Comment by Skillz4Killz** [comment]
@UnseenFaith Embeds in language files would be an even better idea. As I said my method may not be the best case but hopefully, it can spark an idea like you just had of embeds in language files. That's brilliant in my opinion.

@tech6hutch Every user has their own taste. Some may like to use embeds some don't. But that should be up to each individual user to decide in my opinion.

**Comment by kyranet** [comment]
A far more coherent way of doing this: transfer `commandInhibited` to send an embed.
https://github.com/dirigeants/klasa/blob/master/src/events/commandInhibited.js

**Comment by UnseenFaith** [comment]
@kyranet That doesn't solve the issue. You'd want it to be consistently the same throughout the entire bot. The language file is probably the easiest way of doing this.

**Comment by bdistin** [comment]
This goes against a core design principle of klasa found here: https://github.com/dirigeants/klasa/blob/master/.github/CONTRIBUTING.md#klasa-concept-guidelines

**Comment by Skillz4Killz** [comment]
@bdistin I truly respect that it has always been a rule and I hope this can try and show the negative effects for users that the rule can cause.

`Nothing in core should respond with embeds or be terribly "personalized". Instead everything should be an abstract working base that people can personalize themselves to their own needs.`

What I am saying is the second half of this: `Instead everything should be an abstract working base that people can personalize themselves to their own needs.`

Everything should be flexible enough that users can personalize. I am not saying klasa must send embeds or don't send embeds but the option to allow embeds without having to transfer the entirety of klasa and maintain it should exist. Klasa should be able to support the usage of embeds if the developer should need it for whatever reason.

**Comment by tech6hutch** [comment]
Would accepting embeds from language files violate that design principle? I mean, I'd rather keep embed stuff out of language files, but if it's the easiest way to customize core responses...

**Comment by UnseenFaith** [comment]
Alternative Option: Change message.sendLocale/<Channel>.sendLocale to send embed.

**Comment by bdistin** [comment]
From the code, it already should assuming you return a MessageEmbed from your Language file...

**Comment by tech6hutch** [comment]
It doesn't; I ran into that problem before. IIRC, it sends [object Object].

**Comment by UnseenFaith** [comment]
```js
	sendLocale(key, args = [], options = {}) {
		if (!Array.isArray(args)) [options, args] = [args, []];
		const language = this.guild ? this.guild.language : this.client.languages.default;
		return this.send({ content: language.get(key, ...args), ...options });
	}
```
It doesn't work for any of the extended classes for this.

**Comment by bdistin** [comment]
That looks old, unless that's the extendable...

**Comment by bdistin** [comment]
ok, after those commits:

![img](https://puu.sh/C4uJy/afb2e6a9bc.png)

**Comment by bdistin** [comment]
Does this address your concerns? or are you still asking for something more?

**Comment by Skillz4Killz** [comment]
I will test this on my bot and see if it covers all use cases. If there is anything that is not covered I will let you know but I believe this is a good solution already!
