### ISSUE TITLE
this.client.options.production Rename Needed

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#514]
### Describe the issue
This is the code from the unhandledRejection event:

```js
init() {
		if (this.client.options.production) this.disable();
	}
```
To some(probably most) developers, production means the bot is being used by users. In my team, we consider our bot thats on thousands of server as the production bot and we all have our own dev bots. I encountered this dilemma when I was trying to find a way to send webhook logs to a channel ONLY if the bot is production. I went through the docs and found there was an option for "production" and almost set it to true on our "production" bot.

Realistically speaking this name of `production` should be changed to `this.client.options.disableUnhandledRejection`. Or whatever name someone else can find better fit to this.

**Side Point:**
To be honest, even then this option makes absolutely zero sense to me. As I have understood it, disabling this allows your bot to crash as the process will shut down if an error occurs. What benefit does any developer gain from disabling this? If you have a **truly** production bot where EVERYTHING is handled then this disable does nothing cause you won't ever use it. What harm does having this event enabled do to a true production bot? Only thing it does is harm 99% of the bots that might set this to true when not ready and cause those bots to crash. Like why would anyone want to even crash their bot??? It makes no sense to me to even have this in core klasa. This is probably something that <1% of klasa users would ever want to have and in my opinion should not be in core Klasa. Just my 2 cents.

**NOTE** Please note my issue is about renaming not removing. Whether it is removed is up for discussion  but I am hoping to have this option renamed please so that 99% of developers that consider their live bots as production don't confuse this and get their bots crashed and we can use this.client.options.production in other parts of the bot.

Thank You!

### Further details

- **discord.js version**: master
- **node.js version**: 10.4
- **Klasa version**: master
- [x] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by tech6hutch** [comment]
Perhaps the console output should be changed to include a message like "This is an unhandled rejection! This should never happen, if you're properly catching your errors."

**Comment by bdistin** [comment]
unhandledRejection event is "dev training wheels" in a truly production node application you don't use it. The option is properly named, if you want to add behavior beyond that, you can use that, or a different name if you don't want the two linked.
