### ISSUE TITLE
Klasa Sharding Manager

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#524]
### Describe your proposal
Klasa should separate all `broadcastEvals` and any sharding related functionality into a separate piece/store that would serve as Klasa sharding manager. Any time something needs to be done across all shards it would be done through this manager. Imagine a similar functionality to SG and providers system. You can change to whatever database and the code stays the same. Similarily you could change to any "sharding manager" and the code stays the same.

### Use-Cases for your proposal
Not all bots user Discord.js sharding system and broadcastEvals. It would be nice not to have to transfer pieces just to have to change the broadcastEval into the bots sharding system. As an example, I would not have to transfer the reload command. The only reason it gets transferred is because of the sharding system. The less things that need transferring means the less maintaince of Klasa core files are needed which makes using Klasa a thousand times better.

### Expected and actual behavior
Expected: Any easy way to handle sharding where you can only need to transfer a "Sharding Manager" and customize this to whatever way you handle the shards and not need to transfer so many parts of Klasa.

Actual: All files that work across shards need to be transferred and maintained so long as

**Comment by bdistin** [comment]
I have no intention of changing the standard d.js sharding for another system in Klasa (A pillar of Klasa's design, not to change d.js).

However, that doesn't preclude you from making a plugin to easily share the ability to use different sharding, such as @Dev-Yukine 's sharding manager. And with that plugin, you can add a core command directory, which should take precedence over the core commands. In that directory, you can include commands such as reload etc with the updated way of updating the other shards of that plugin/manager.
