### ISSUE TITLE
Memory leak while reading json

### ISSUE THREAD

**Issue by BannerBomb** [dirigeants/klasa#533]
### Describe the issue
While loading multiple json files using the json provider causes a memory leak, 10 small (about 100KB file) json files causes 1GB of memory, in which the memory just keeps rising rapidly after around 5-10 seconds of the project running.

### Code or steps to reproduce

```js
N/A
```

### Expected and actual behavior
It would be better so while reading from the json files it would release it's memory after each file it reads.

### Further details

- **discord.js version**:
discord.js-dev (master) v12
- **node.js version**:
Node v11.3.0 (latest)
- **Klasa version**:
klasa-master (`98b183b612e00aad7fa1e9b2bd28dd9aaeafb433`)

- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
cc @bdistin

**Comment by bdistin** [comment]
I and many others have bots that use the included json provider and have never seen anything close to what you are describing (or a memory leak at all tbqh). FS-Nextra doesn't cache anything, neither does the json provider, SG caches settings fetched from the provider on Settings instances on your d.js guild/user objects which is fully intended (so you have a natural buildup, but not a leak), and the memory is released if they are uncached. So I can't see how there could be a "leak" as you describe with the details you provide.

The only thing that you have said that I cannot confirm, is you are using 11.3.0 node, and I haven't used that specific version. It is possible that they have made changes to fs-promises, and inadvertently created a memory leak in node itself. If that's the case, then it's nothing we can fix, rather a Node bug. But that's speculation on a lack of details.

Could you use a tool such as [ndb](https://www.npmjs.com/package/ndb) to inspect your heap, and provide better details?

**Comment by BannerBomb** [comment]
I'll get a heap when I get home, but the memory buildup doesn't occur when I remove all the saved json files and run the program or if I take away 3 of them it doesn't happen, but then I go to add them back and try again and it rises to 1GB. I have tried downgrading back to nodejs 10.14.1 and 10.14.0 but the issue persists unless I keep the json file amount to a minimum. And each json file is only around 100-300KB in size. But I will provide more detail when I get back to the house.

**Comment by BannerBomb** [comment]
I am running the bot on my ubuntu laptop currently because it makes it easier to manipulate files.

This is my memory before I run the bot.
![image](https://user-images.githubusercontent.com/11788894/49616693-ac333500-f97f-11e8-8d0d-117db7ae66a5.png)

This is my memory during the running of the bot after (5 seconds of it running)
(i will edit once bot connects to websocket successfully again)


heap timeline
[Heap-20181206T174959.zip](https://github.com/dirigeants/klasa/files/2655219/Heap-20181206T174959.zip)

heap snapshot
[1544130988451-heapsnapshot.zip](https://github.com/dirigeants/klasa/files/2655220/1544130988451-heapsnapshot.zip)

**Comment by bdistin** [comment]
1. Not going to open that file attachment for security reasons.
1. If it is legit a heap snapshot, you just leaked your bot token.

**Comment by BannerBomb** [comment]
it's ok I can change my bot token, this is the content of the 2 json files
```json
{"id":"236902633430974464.80821761460928512","regexes":[":?^|\\s(thew(some)?)"]}
```
```json
{"id":"236902633430974464.116293018742554625","words":["jake","mod"]}
```
the above 2 are the ones I removed to fix the crashing, but they are just like my other json files which are basically contain.
```json
{"id":"305129477627969547.80821761460928512","words":["thewsome"],"blacklistedUsers":["465676088798871552","320726348656148482"],"regexes":["(<@&306075275685265408>)","(<@&346489501339746305>)"],"blacklistedRoles":["306075275685265408"]}
```
It crashes once the json files reach a max of 13 json files that the bot has to read from. Yet the bot can handle 12 files just fine without the bad_alloc showing.

**Comment by BannerBomb** [comment]
nvm, the number of files doesn't matter I went back and tried only using the 2 json files I took out and it did the same thing with the bad_alloc so it seems to be one of those 2 causing it.

**Comment by bdistin** [comment]
The one with just jake/mod should be good, betting that other with the regex is the one causing your issue

**Comment by bdistin** [comment]
The best advice I can give you is, don't let your bot's users have custom regex highlights. It's a vulnerability, for exactly the reason you made this issue.
