### ISSUE TITLE
Proposal: New `download-piece` core command

### ISSUE THREAD

**Issue by cfanoulis** [dirigeants/klasa#534]
### Describe your proposal
I'd like to see a `+download-pieces` command, that would download and/or update pieces from the [klasa-pieces](https://github.com/dirigeants/klasa-pieces) repository. The command would only be accessible by the bot owner (permission level 10).

### Use-Cases for your proposal
- An owner wants to download a piece from the klasa-repository without the hassle of having to open a computer
- An owner sees a command on the klasa-pieces repository was updated, and wishes to swifty update it on his bot as well (a true example of this: The amazing [reboot command](https://github.com/dirigeants/klasa-pieces/blob/master/commands/System/Admin/reboot.js) by Hutch)

### Expected behavior
- The owner issues the command with arguments `typeof` which is one of `argument|command|event|extenable|finalizers|inhibitor|language|monitor|provider|route|serializer|task` (possibly with an argument type instead of a literal - tbc) as well as the piece's name
- If the piece is installed, the bot confirms that the owner wishes to have the piece updated, as well as informs him/her that any customization **will** be lost. Then, it proceeds with updating.
- If the piece is not downloaded, the bot will prompt to download the piece from the repository, as well as its dependencies (see **Further Details**)

### Further details
Please do note that this would imply a new format for a klasa-piece, as it would need to define it's dependencies in a machine-readable format, prefferably as a comment on the 2nd line (since the 1st line is reserved for the licence notation).

**Comment by UnseenFaith** [comment]
Chances of this happening are probably going to be low. We've already tried this experiment before with Komada and it led to a lot of issues and a bunch of headaches in the process.

**Comment by bdistin** [comment]
As faith has stated, this has been done before, caused endless headaches, and was intentionally excluded from Klasa for those reasons.
