### ISSUE TITLE
Handling Language File Breaking Changes

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#600]
### Describe the issue
2 Things here:

1) Language file changes must be documented as breaking when adding or removing keys. There have been a lot of changes made to the en-US.js file in the last few months since the last time I updated Klasa. This broke since my bot uses the en-US.js file. I had no way of knowing that there were keys added or removed since it was not announced. 

2) I have a check that sends me an error report when a key is missing but klasa does not have this check by default meaning every other developer using klasa is going to have issues. Their users are going to get an error saying `XXXXX has not been localized to en-US` but the developers are never made aware that the key is missing. This is an error that needs to be sent to the developer not the user. 
![image](https://user-images.githubusercontent.com/23035000/53348786-b82cf400-38e9-11e9-864c-57d36772e601.png)

### Expected and actual behavior

Expected: 
Klasa should warn developers(not only users) when a key is missing. It only warns users. I have this built into my bot now but this is something seriously in need of a change in core itself.

Actual:
Klasa sends a reply to the **user** and not the developer. The developer is NEVER made aware that the key is missing 🤦‍♂️ 

Expected:
Changes to language files break as most bots will have en-US.js transferred. Changes in this file are breaking and need to be announced as breaking changes. Or atleast logged a LOT better and developers made aware of these changes and new keys.

### Further details

- **discord.js version**: Latest
- **node.js version**: Latest
- **Klasa version**: Latest
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: 3c7779879da64865dc3590cfab35b7cabc03b0d1

**Comment by bdistin** [comment]
The key you are complaining about in support chat hasn't been touched in 5 months. The only things touched recently are privately used by Klasa, and does not affect individual en-us files. Additional strings are not breaking changes because you don't have support for them in other files, it's always a feature to add new stuff. Making this entire issue invalid.
