### ISSUE TITLE
Adding multiple duplicate items to a SG array

### ISSUE THREAD

**Issue by gc** [dirigeants/klasa#614]
### Describe the issue

I can't seem to add multiple duplicate values to a SG array, e.g. `["string", "string"]`, is there a way to do this?

### Code or steps to reproduce

These are what I tried to do. Both of these snippets are ran when `author.settings.badges` is `["EASTER_EGG"]`, neither of them change that
```js
msg.author.settings.update("badges", "EASTER_EGG", { action: 'add' });
// Errors: [The value EASTER_EGG for the key badges already exists.]
// Updated: []

const newBadge = "EASTER_EGG";
const currentBadges = msg.author.settings.get("badges");
const newBadges = [...currentBadges , newBadge];
console.log(newBadges); // [ 'EASTER_EGG', 'EASTER_EGG' ]
msg.author.settings.update("badges", newBadges);
// Errors: []
// Updated: [ {
//    data: [ 'badges', [ 'EASTER_EGG' ] ],
//    piece: SchemaPiece } 
//    ]

```

### Expected and actual behavior

It's not a bug (I think), but I expected that duplicate items could be added in some way, even if it requires a special way to do it

### Further details

- **discord.js version**:
- **node.js version**:
- **Klasa version**:
- [ ] I have modified core files.
- [X] I have tested the issue on latest master. Commit hash:

**Comment by kyranet** [comment]
You can use overwrite while it's bugged (doesn't check for duplicates).

You should suggest this in #425 though

**Comment by bdistin** [comment]
closing this in favor of the existing issue #425
