### ISSUE TITLE
[TYPO] Mistake in function msg.hasAtleastPermissionLevel(#)

### ISSUE THREAD

**Issue by Kashalls** [dirigeants/klasa#63]
Apparently, on the docs, it shows this for checking the Permission level of a msg.

`msg.hasAtleastPermissionLevel(#)`

However, when testing this it ends up returning: 
`0|app      | [2017-10-24 19:12:40] TypeError: msg.hasAtleastPermissionLevel is not a function
0|app      | [2017-10-24 19:12:40]     at module.exports.run (/home/jordan/Sistine/commands/Currency/balance.js:38:31)
0|app      | [2017-10-24 19:12:40]     at msg.validateArgs.then (/home/jordan/Sistine/monitors/commandHandler.js:66:19)
0|app      | [2017-10-24 19:12:40]     at <anonymous>
`

The function ends up working if you capitalize the l in Atleast to AtLeast. 
[https://dancing.while-at.work/3f4e0f.png](https://dancing.while-at.work/3f4e0f.png)

**Comment by bdistin** [comment]
It's Atleast. Feel free to pr the correct capitalization to the docs.
