### ISSUE TITLE
teams support

### ISSUE THREAD

**Issue by bdistin** [dirigeants/klasa#632]
### Describe your proposal
This would replace `client.owner: KlasaUser` with `client.owners: Set<KlasaUser>`. This will alter all internal uses of client.owner to give full permissions to everyone in the owners set. This will be filled from the future API endpoint described here <https://github.com/discordapp/discord-api-docs/issues/787>

Edit: going to use a Set for owners instead.

**Comment by cfanoulis** [comment]
this didnt close with #732?
