### ISSUE TITLE
List Subcommand In Blacklist Command

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#678]
### Describe your proposal
It would be really nice to have a `list` subcommand to the blacklist command. 

### Use-Cases for your proposal
Sometimes blacklisted users come asking why the bot doesn't respond long after they became blacklisted. It is hard to remember every user/guild so it would be nice to have a simple command to remind our support/devs that they are blacklisted.
### Expected and actual behavior
N/A

### Further details
N/A

**Comment by bdistin** [comment]
This would be too customized to be included with the framework, you could, however, write a piece like this for klasa-pieces.
