### ISSUE TITLE
Command|Category prefix overwrite

### ISSUE THREAD

**Issue by TheLearneer** [dirigeants/klasa#702]
### Describe your proposal
Ability to have prefix for command category. Or well even maybe per command prefix.

### Details for your proposal
Useful for multipurpose bots when want to better categorize the responses.

For eg. Considering a bot with both moderation and entertainment modules.
Doing `mod!kick` etc would trigger the moderation command `kick`, while `fun!joke` would trigger the entertainment command `joke`.

___Yeah I am aware there is no such use for such basic stuffs, but considering the large scale modules this can be preety helpful.___

This would also help better to explain the categories better:
`mod!help` would display moderation category help and `fun!help` would display entertainment category help.
But well `!help` can already display the default help command(_Considering ! is the default prefix_)

Yup I am aware of the few problems that might occur during the implementation:
- _`Guild based prefix settings`_ :: Not sure how to overcome this.
- _Few other problems that had strike my mind when I was bored in class but I forgot now :sweat_smile:_

_NOTE: Yup I basically got to this idea from [Akairo](https://discord-akairo.github.io/#/docs/main/master/class/Command?scrollTo=prefix), because When I was experimenting with akairo back in decades for about a month, it was preety useful, and I feel as if this can be a good add-on to Klasa as well._

**Comment by tech6hutch** [comment]
An interesting proposal. Generally, I think taking multiple prefixes for your bot is impolite, and brings increased risk of overlap. (E.g., go into a bot guild and do `!help`.) Not so bad if they can be configured, I suppose.

Also I wonder about the impact to performance, with parsing multiple prefixes on every message.

**Comment by tech6hutch** [comment]
Building on this, tho, here's an idea: the different category prefixes could be automatically generated based on a "base" prefix. E.g., in your example, the base would be `!`.

**Comment by TheLearneer** [comment]
Well I do agree that multiple prefixes for a bot is impolite and brings increased risk of overlap, but If they are properly selected that has low possiblities..

Like I stated in example above: `mod!` and `fun!`.
Ok being more specific with the case I would love to have it in my bot is `cr!` or `royale!` for the clash royale specific commands (Which are lot)

Also I do agree that it _might_ have impact on performance having to parse multiple prefixes on every message. (But well every good thing has a bad side as well)

Yup another possiblity is also having the prefix generated based on the base preix.


**NOTE**: _Yeah and another problem that I was thing of was the command name conflict. when two different category command can have same name but different base prefix.. It can be treated with providing different name, but executing command with same name but different prefix would also be a cool addon._

**Comment by tech6hutch** [comment]
Probably the best way to accomplish that would be changing client.commands to be a nested structure, with each CommandStore containing the prefix its commands use.

**Comment by TheLearneer** [comment]
Well I am completely unsure how to achieve this, but I just suggested this idea as I felt it's gonna be a good feature for the klasa framework (**IMO**) and would benefit other users as well. :+1:

**Comment by Skillz4Killz** [comment]
Maybe im confused but isnt this already possible in a way?

Use SG to create a setting where each guild can store their custom prefixes for each category.
```js
  mod: "mod",
  royale: "cr",
```
Then in all your royale commands
```js
const categoryPrefixes = message.guild.settings.get('categoryPrefixes')
if (!message.content.startsWith(categoryPrefixes.royale)) return null
```

This way the commands would silently error out whenever used without that category prefix. 

In order to work someone would have to type `cr!commandName args`

**Comment by kyranet** [comment]
To be fair, empty prefixes are already possible in Klasa (`prefix: null`, which is the default value), so you could make `prefix` unconfigurable doing

```js
KlasaClient.defaultGuildSchema
    .get('prefix').edit({ configurable: false });
```

So it doesn't get modified by the help command, and furthermore, you'd do @Skillz4Killz's suggestion with one tweak: you have to modify the commandHandler to check for prefixes, then trim off the prefix and everything else.

This should be pretty straightforward and I believe this is completely doable in a plugin, if somebody wants to do it.

**Comment by bdistin** [comment]
Actually, everyone here is overcomplicating it. No need to modify core at all (through extendable or otherwise) to achieve this in your bot.

Let me preface that **this will not be added to core** as it's against bot best practices (the general idea, not the following implementation).

In your client options, for prefix set an array of all the prefixes you want to use. In your guild schema make prefix `configurable: false` as Kyra has stated. Then make a prefixCategory inhibitor. See at this point you have both the prefix used and the command category (and subcategory, etc), so from there you just filter which prefixes are applicable to which categories, and either inhibit the command or let it run.

**Comment by TheLearneer** [comment]
Thanks everyone for the replies. Helps me to get the directions I wanted :smile:
