### ISSUE TITLE
SettingsError Event

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#708]
### Describe your proposal
It would be really nice to have a event that is emitted whenever there is some error in Settings.

### Use-Cases for your proposal
This is the current way of handling errors. Duplicate this over 100s of files on larger bots and you get a lot of extra lines that just are not needed if there was a nice event handler for these errors.
```js
const { errors } = await settings.update(key, value, options)
if (errors.length) this.client.emit(`error`, errors.join(`\n`))
```

*Current Workaround*: Using the functions plugin
```js
await this.client.helpers.update(key, value, options)
```

### Expected and actual behavior
It would be nice to do something like below and any and all errors are emitted in the `settingsError` event.
```js
await settings.update(key, value)
```

### Further details
N/A

**Comment by kyranet** [comment]
I disagree to this, but I see an usecase for a `settingsError` event: when the sync fails, which is currently not handled correctly, and could use some easy management:

https://github.com/dirigeants/klasa/blob/99eeec82eb13980a04d52782ea3cc8f799131f14/src/lib/settings/gateway/Gateway.js#L73

**Comment by Skillz4Killz** [comment]
```js
			const { errors } = await guild.settings.update(key, value)
			if (errors.length) this.client.emit('error', errors.join('\n'))

			const updatedUser = await user.settings.update(key, value)
			if (updatedUser.errors.length) this.client.emit(`error`, updatedUser.errors.join(`\n`))

return null
```

VS:

```js
await guild.settings.update(key, value)
return user.settings.update(key, value)
```

7 lines down to 2 lines of code. Individually handling emitting errors is kinda weird. If the `settingsError` event is for another use case, it would also be possible to do it other ways.

```js
await guild.settings.update(key, value, { emitErrors: true })
return user.settings.update(key, value, { emitErrors: true })
```

Then somewhere in the `update` method you can do
```js
if (options.emitErrors && errors.length) client.emit.......
```

**Comment by kyranet** [comment]
Alternative, using what's already available in the Settings branch:
```js
await guild.settings.update(key, value, { throwOnError: true });
await user.settings.update(key, value, { throwOnError: true });
```

**Comment by tech6hutch** [comment]
Other possibilities:

* You could make a function that handles the errors, if any, and pass it to Promise#then: `await guild.settings.update(key, value).then(handleErrors)`

* You could make an extendable on SettingsFolder#update

**Comment by kyranet** [comment]
@Skillz4Killz are the current (and next with #752) enough satisfactory to close this issue?

**Comment by Skillz4Killz** [comment]
@kyranet I believe throwOnError solved all my needs already.
