### ISSUE TITLE
Transferable Pieces Should Not Use Private Functions

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#770]
### Describe the issue
In my opinion any piece that can be transferred should not use private functions. Once it is transferred then it becomes quite a pain to have to fix that. Either we also need to move the entire Class where those private methods are or we need to add ignores to the files which isn’t ideal either.

**Solution:**
Change any methods used in Pieces to be public.

### Code or steps to reproduce

```js
run(message: KlasaMessage, command: Command) {
	if (this.client.owners.has(message.author) || command.cooldown <= 0) return

	const existing = command.cooldowns.get(message.levelID)

	if (existing && existing.limited)
		throw message.language.get("INHIBITOR_COOLDOWN", this.secondsToFormattedString(Math.ceil(existing.remainingTime / 1000)), command.cooldownLevel !== "author")
}
```

### Expected and actual behavior
![image](https://user-images.githubusercontent.com/23035000/61914830-e7cf3f00-af0f-11e9-8991-f727990d550c.png)

### Further details

- **discord.js version**: master
- **node.js version**: 10.15
- **Klasa version**: settings branch
- [ ] I have modified core files.
- [ ] I have tested the issue on latest master. Commit hash:

**Comment by MrJacz** [comment]
@Skillz4Killz you realise you could just PR a fix to the typings by making them properties public?

**Comment by Skillz4Killz** [comment]
@MrJacz is this something that would be accepted? I would be happy to make the PR, I just wasn’t sure if things like this would be accepted to be made public because it can cause Klasa to have to handle certain things different with SEMVER.

**Comment by MrJacz** [comment]
@Skillz4Killz this has nothing to do with SEMVER.
You're always better off making a PR.
