### ISSUE TITLE
Reprompting bug back again :D

### ISSUE THREAD

**Issue by MrJacz** [dirigeants/klasa#78]
well oops basically https://i.imgur.com/ravkASt.png 

when i go to edit a cmd and do the 1st optional argument prompts when it shouldn't

**Comment by MrJacz** [comment]
welp

**Comment by MrJacz** [comment]
Welp

**Comment by MrJacz** [comment]
it would be around https://github.com/dirigeants/klasa/commit/78b96b90bba8344303d008bb37f18cd2d7266702 to https://github.com/dirigeants/klasa/commit/b6df5b58161d9335412801559ec3c3af1594a159

**Comment by kyranet** [comment]
Can you reproduce this issue? If not, I can check it later and PR a fix.

**Comment by MrJacz** [comment]
I'm on latest master of Discord.js and Klasa ```js
const { Command, Stopwatch } = require("klasa");
const { inspect } = require("util");
const discord = require("discord.js"); //eslint-disable-line

module.exports = class EvalCommand extends Command {

    constructor(...args) {
        super(...args, {
            aliases: ["ev"],
            permLevel: 10,
            description: "Evaluates arbitrary Javascript.",
            usage: "[Depth:integer{0,3}] <expression:str> [...]",
            usageDelim: "",
            extendedHelp: "No extended help available."
        });
    }

    async run(msg, [depth = 0, ...code]) {
        const client = msg.client; // eslint-disable-line
        const guild = msg.guild; // eslint-disable-line 
        const settings = this.client.settings; // eslint-disable-line
        const start = new Stopwatch();
        try {
            const evaled = eval(code.join(" "));
            let ogeval = evaled;
            if (evaled instanceof Promise) ogeval = await ogeval;
            if (typeof evaled !== "string") ogeval = inspect(ogeval, { depth: depth, showHidden: true });
            const cleanEval = this.client.methods.util.clean(ogeval);
            if (ogeval.length > 1950) {
                const haste = await this.client.haste(cleanEval, "js").catch(console.error);
                msg.send(`**Took:** \`${start.stop()}\`, **Typeof:** \`${typeof evaled || evaled.constructor.name}\`
\`Input:\`
${this.client.methods.util.codeBlock("js", code.join(" "))}
\`Output:\` **Evaled code was over 2000 letters Here yo go **${haste}`).catch(console.error);
            } else {
                msg.send(`**Took:** \`${start.stop()}\`, **Typeof:** \`${typeof evaled || evaled.constructor.name}\`
\`Input:\`
${this.client.methods.util.codeBlock("js", code.join(" "))}
\`Output:\`
${this.client.methods.util.codeBlock("js", cleanEval)}
`).catch(console.error);
            }
        } catch (err) {
            msg.send(`
**Took:** \`${start.stop()}\`
\`Input:\`
${this.client.methods.util.codeBlock("js", code.join(" "))}
\`Error:\`
${this.client.methods.util.codeBlock("js", err)}`).catch(console.error);
            if (err.stack) this.client.emit("error", err.stack);
        }
    }

    async init() {
        this.depth = 0;
    }

};
``` is the code

**Comment by bdistin** [comment]
You have no usage delim with multiple args...

**Comment by MrJacz** [comment]
i did just removed it inthat code

**Comment by MrJacz** [comment]
I'm quite unsure what could be causing this

**Comment by bdistin** [comment]
can you reproduce in v0.5.0 (probably try the sg rewrite branch)

**Comment by MrJacz** [comment]
I'll try soon :D

**Comment by MrJacz** [comment]
Still getting it, https://i.imgur.com/r4tmCvu.gif the code for the eval command: https://hastebin.com/iyaqavagex.js

**Comment by MrJacz** [comment]
Latest commit on Discord.js and Klasa#master https://i.imgur.com/XXRiTiY.png

**Comment by kyranet** [comment]
@MrJacz can you reproduce this bug in #136, or is it fixed?
