### ISSUE TITLE
Discord Invite Link

### ISSUE THREAD

**Issue by ZacharyMurphy** [dirigeants/klasa#781]
The Discord Invite link is dead.

**Comment by Skillz4Killz** [comment]
Confirmed issue ^

**Comment by ZacharyMurphy** [comment]
Is there any fix yet?

**Comment by MrJacz** [comment]
CC @bdistin

**Comment by bdistin** [comment]
It's known, donated domain expired... I haven't spent the time or money to fix it as I don't have any extra of either atm. For now, you can use this: https://discord.gg/AnvgbFr

**Comment by bdistin** [comment]
This has been fixed... You may need to hard refresh to get the latest version of the website for the invite to work.

The above invite is now retired.

**Comment by Satont** [comment]
Still not working.

**Comment by bdistin** [comment]
just checked, it is indeed working.

**Comment by Satont** [comment]
![1](https://cdn.satont.ru/s/9PYLN7.png)
Link on https://klasa.js.org just open empty modal
![2](https://cdn.satont.ru/s/TECNGG.png)

**Comment by MrJacz** [comment]
@Satont try clearing your cache on the site, its working for me

**Comment by bdistin** [comment]
Yes, Anv.... has been removed. But the website is generating invites, it seems you didn't leave that modal open long enough, or some error for using a non-mainstream browser happened... But I can see that the invite was generated in the guild.

![img](https://puu.sh/Ee9Ru/79ef51edeb.png)

**Comment by Satont** [comment]
Ok, i just need to wait some for join. It's not `intuinitve`. Thx guys.
