### ISSUE TITLE
Per-Guild Command/Command Category Enable/Disable

### ISSUE THREAD

**Issue by naterchrdsn** [dirigeants/klasa#803]
### Describe your proposal
Allow guild owners/admins to disable/enable commands and command categories in their guild

### Use-Cases for your proposal
There are millions of bots out there, and a lot of overlap between them. Giving guild owners an opportunity to disable features in your bot (when using the Klasa framework) is a great way to make sure that your bot sticks around on their server rather than getting phased out in favor of something else

### Expected and actual behavior
`disable commandName` => when run by guild owner, disables the command or command category in their server only

same with enable

**Comment by bdistin** [comment]
This is very easy to do on your own. Create a disabledCategories setting as `string` with `array: true` on the DefaultGuildSchema, and an inhibitor that simply does `return msg.guild && msg.guild.settings.get('disabledCategories ').includes(command.category)`. That's all you need and that even updates the help for those guilds. This is something that will not be included in the core library, so I am closing this issue.

**Comment by naterchrdsn** [comment]
That's, absolutely amazing. Thanks for the tip!
