### ISSUE TITLE
NPM listing is out of date

### ISSUE THREAD

**Issue by Rexogamer** [dirigeants/klasa#811]
### Describe the issue
The NPM listing of Klasa is still on 0.4.0, and was last updated ~2 years ago.
### Code or steps to reproduce
- Go to the [NPM listing](npmjs.com/package/klasa)
#### Expected: 
It should have 0.5.0-dev (or anything later than 0.4.0).
#### Actual:
It has 0.4.0

I understand that 0.5.0 is in dev, but this concerned me.

**Comment by vladfrangu** [comment]
The npm version is currently outdated, and we know that. From what I gathered, a release is planned once discord.js v12 is also released, and we finish a couple of our PRs. For now, we recommend installing the v1.0.0-alpha branch (or settings branch).

**Comment by yuta0801** [comment]
Now Discord.js v12 has been released. Is there any update?

**Comment by kyranet** [comment]
Quote from @bdistin:

> Klasa is abandoning d.js, it's in a degraded state

**Comment by yuta0801** [comment]
Does that mean the next klasa version does not have discord.js dependency?

**Comment by kyranet** [comment]
Currently there's no branch of Klasa that does not depend on discord.js, as we're still working on [Project Blue](https://github.com/dirigeants/Project-Blue)
