### ISSUE TITLE
Suggestion: awaitMessage Tool

### ISSUE THREAD

**Issue by Skillz4Killz** [dirigeants/klasa#87]
There are some really good stuff on Klasa that use reactions and paginations and make life a lot more easier and amazing with stuff like RichDisplay and RichMenu.

I was wondering if there was a chance of incorporating something similar for awaitMessages. I use this as an application of sort and was hoping for an awesome way to do this.

it would require parameters like:
an object that shows how many different questions you need to be answered, time for each question, type of response like options which could use reactions etc

Let me know if I am not clear on the suggestion and would like more details I will be happy to elaborate.

**Comment by kyranet** [comment]
There was a plan about making an awaitMessage tool which use is similar to the commands' usage months ago, but it never got done. It was going to be something like:

```javascript
awaitMessage('<minutes:integer{5,20}> <reason:string> <user:mention>');
```

Althought it was @pedall's suggestion if I remember correctly.

**Comment by tech6hutch** [comment]
I made something kind of similar, but it's much simpler, for only getting a single reply. https://github.com/dirigeants/klasa-pieces/pull/15

**Comment by bdistin** [comment]
It's part of the 1.0.0 plan. Just not done. Waiting on changes some changes to d.js which may cause me to rewrite usage anyway. Avoiding rewriting it twice for this purpose and the changes coming to CommandMessage.
