### ISSUE TITLE
Klasa ReactionHandler unstable behavior when messages are deleted

### ISSUE THREAD

**Issue by Lovinity** [dirigeants/klasa#870]
### Describe the issue
Let's assume there is a command !richmenu. It uses a Klasa RichMenu to prompt the user to select an option. After selecting an option, the collector message is deleted, and a new RichMenu is used to make a new prompt based on the previous selection.

When collector.message.delete is used between RichMenu instances within the same command call, the ReactionHandler becomes unstable due to an "Unknown Message" Discord API error. This sometimes results in the next RichMenu having no bot reactions (although it will still work if a user manually adds a reaction pertaining to an option or another page).

My suggestion is to either have a catch for this in ReactionHandler, or documentation to explain the user should not use collector.message.delete() until no more menus will be provided within that function / command call.

### Code or steps to reproduce

See https://github.com/Lovinity/the-meditation-station-bot/blob/ccc34116ecfa11fbb81ba460b2dad413daefc760/commands/Moderation/cases.js for example code where this issue exists (I removed the collector.message.delete calls and changed the message.channel.send to message.send in the menu.run calls in a later commit, which stopped the issue from happening anymore).

### Expected and actual behavior

Expected behavior:
If a collector.message.delete() is called and another RichMenu or ReactionHandler is used in the same function/command call, Klasa creates / sends a new message, and then processes the reactions on the new message.

Actual behavior:
Klasa does create / send a new message in the above instance (at least when using message.channel.send; have not tested this issue with message.send), but it tries to process reactions on the previously deleted message instead of the newly sent message. This obviously fails with a Discord.js Unknown Message error, therefore the bot does not add any reactions. However, the ReactionHandler still correctly monitors for user reactions on the new message.

### Further details

- **discord.js version**: github:discordjs/discord.js#3a9eb5b92928631edc79e09894ba6bbad90516f7
- **node.js version**: 12,13,0
- **Klasa version**: github:dirigeants/klasa#0e9174cab0df7d28f3a7b8ca78b6344fef2611c9
- [ ] I have modified core files.
- [x] I have tested the issue on latest master. Commit hash: #0e9174cab0df7d28f3a7b8ca78b6344fef2611c9

**Comment by bdistin** [comment]
Stop using `var` and your problem will go away

**Comment by Lovinity** [comment]
Thank you, however I would have appreciated a less condescending and more educational response. Although I know a little bit about variable scopes via. const, let, etc, it cannot be assumed everyone you speak with does. More especially, I would like to know how variable scopes affect Klasa's use of messages. So telling me to stop using "var" without also suggesting other ways to use variables is not very helpful. I appreciate you taking the time to read and consider my request.
