### ISSUE TITLE
Suggestion: Better usage of moment.js

### ISSUE THREAD

**Issue by kyranet** [dirigeants/klasa#89]
For a long time, we have depended of the [moment](https://www.npmjs.com/package/moment) package, however, its i18n support is not used, as well as it is a bit hard to use, check the reference [here](https://momentjs.com/docs/#/i18n/instance-locale/). We could do two things:

- 1.- Remove moment as a dependency and make our own one, this would be very similar to what we did with chalk before (thanks to Faith), and we could get rid of many weird issues when using `moment-duration-format`. Then, our implementation could be more efficient with the latest V8 changes and easier to use.

- 2.- Modify our usage of moment so it's multilanguage. (It is used in the stats command to show how long has a bot been running for).
https://github.com/dirigeants/klasa/blob/12616ee190fb74284ae28840603153e708549c7b/src/commands/System/stats.js#L16

**Comment by bdistin** [comment]
We actually don't use moment-duration-format in klasa. Our only 2 deps are fs-nextra and moment. It's true we don't even use moment that much however.

**Comment by kyranet** [comment]
And the little we use from moment does, however, breaks the language consistency. If you have your bot, for example in Russian, and you run the stats command, you're gonna get a mix of both English and Russian, since moment is running always in English.

Nonetheless it's very used for the console, but I think there's a way to improve the performance for the timestamps

**Comment by kyranet** [comment]
We're also getting a negative report at David-DM with moment.js using an unsecure RegExp constructor:
https://david-dm.org/dirigeants/klasa

**Comment by Pandraghon** [comment]
What about [Luxon](https://github.com/moment/luxon)?

**Comment by kyranet** [comment]
@Pandraghon we're not going to use another dependency but include our own one, the Timestamp class (check #116) fixes build issues and makes the timestamp parsing for the console lightning fast.
